### ISSUE TITLE
failed to compile on debian9

### ISSUE THREAD

**Issue by ymshenyu** [anonymous5l/ncmdump#1]
main.cpp: In function ‘int aes128_ecb_decrypt(const uint8_t*, uint8_t*, int, uint8_t*)’:
main.cpp:49:17: error: aggregate ‘EVP_CIPHER_CTX x’ has incomplete type and cannot be defined
  EVP_CIPHER_CTX x;
                 ^
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by Jerry744** [comment]
I wanna know if the solution works because more issues appeared in mine.
Thanks
g++ main.cpp cJSON.cpp -o ncmdump -lcrypto -ltag -lz
main.cpp:2:7: error: ‘EVP_CIPHER’ does not name a type
 const EVP_CIPHER *cipher;
       ^~~~~~~~~~
main.cpp:3:1: error: ‘ENGINE’ does not name a type
 ENGINE engine; 
 ^~~~~~
main.cpp:6:19: error: ‘EVP_MAX_IV_LENGTH’ was not declared in this scope
 unsigned char oiv[EVP_MAX_IV_LENGTH]; 
                   ^~~~~~~~~~~~~~~~~
main.cpp:7:18: error: ‘EVP_MAX_IV_LENGTH’ was not declared in this scope
 unsigned char iv[EVP_MAX_IV_LENGTH]; 
                  ^~~~~~~~~~~~~~~~~
main.cpp:8:19: error: ‘EVP_MAX_BLOCK_LENGTH’ was not declared in this scope
 unsigned char buf[EVP_MAX_BLOCK_LENGTH]; 
                   ^~~~~~~~~~~~~~~~~~~~
main.cpp:10:6: error: variable or field ‘app_data’ declared void
 void app_data; 
      ^~~~~~~~
main.cpp:13:6: error: variable or field ‘cipher_data’ declared void
 void cipher_data; 
      ^~~~~~~~~~~
main.cpp:16:21: error: ‘EVP_MAX_BLOCK_LENGTH’ was not declared in this scope
 unsigned char final[EVP_MAX_BLOCK_LENGTH];
                     ^~~~~~~~~~~~~~~~~~~~
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by ymshenyu** [comment]
@Jerry744  use golang version instead it
